# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephan Schiffels' Blog
description: blog posts on population genetics, bioinformatics and human history.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stschiff.github.com" # the base hostname & protocol for your site
twitter_username: stschiff
github_username:  stschiff
theme: cayman

# Build settings
markdown: kramdown
